app/models/post.py
from sqlalchemy import ForeignKey
from sqlalchemy.sql import func
from app.extensions import db
from app.models.user import User

class Post(db.Model):
    __tablename__ = "post"
    id = db.Column(db.Integer, primary_key = True)
    author_id = db.Column(db.Integer, ForeignKey("user.id", ondelete = "CASCADE"), nullable = False)
    updated_at = db.Column(db.DateTime(timezone = True), server_default = func.now())
    published_at = db.Column(db.DateTime(timezone = True), server_default = func.now())
    title = db.Column(db.String(100), nullable = False)
    content = db.Column(db.Text, nullable = False)

    def __repr__(self):
        return f'<Post {self.author_id}>'

app/models/user.py
from flask_login import UserMixin
from app.extensions import db

class User(UserMixin, db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(100), unique = True)
    password = db.Column(db.String(100))
    firstname = db.Column(db.String(100))
    lastname = db.Column(db.String(100))
    intro = db.Column(db.String(200), nullable = True)

    def __repr__(self) -> str:
        return f'<User {id}>'

app/__init__.py
# This __init__.py file will hold code for our Flask factory function, which is a function we use to set and create the Flask application instance where you link all your Flask blueprints together. Think of the factory function as the central function in which all our Flask components (blueprints) are combined into one application and that you can use to create different Flask application instances for different purposes with different configurations. For example, you could use the factory function to create a Flask application instance for testing with proper configurations for testing.

from flask import Flask
from flask_login import LoginManager
from config import Config
from app.extensions import db

def create_app(config_class = Config):
    '''Flask application factory function (https://flask.palletsprojects.com/en/2.2.x/patterns/appfactories/)'''

    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initialize Flask extensions here
    db.init_app(app)

    # Specify the user loader which tells flask-login how to find a specific user from the ID that is stored in their session cookie
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from app.models.user import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix = '/auth')

    from app.posts import bp as posts_bp
    app.register_blueprint(posts_bp, url_prefix = '/posts')
  
    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__) # 'main': The name of the blueprint. Will be prepended to each endpoint name.

from app.main import routes # with this, registering a blueprint will also register its routes

app/main/routes.py
from flask import render_template
from flask_login import login_required, current_user
from app.main import bp

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name = current_user.firstname)

app/posts/__init__.py
from flask import Blueprint

bp = Blueprint('posts', __name__)

from app.posts import routes

app/posts/routes.py
from flask import Flask, render_template, request, flash, redirect, url_for
import markdown
from flask_login import login_required, current_user
from app.posts import bp
from app.models.post import Post
from app.extensions import db
from werkzeug.exceptions import abort

@bp.route('/')
@login_required
def index():
    posts = Post.query.all()
    return render_template('posts/index.html', posts = posts, author_id=current_user.id)

@bp.route('/categories')
@login_required
def categories():
    return render_template('posts/categories.html')

def get_post(post_id):
    post = Post.query.get_or_404(post_id)
    return post

@bp.route('/<int:post_id>')
@login_required
def post(post_id):
    post = get_post(post_id)
    return render_template('posts/post.html', post = post)

@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        author_id = current_user.id

        if not title:
            flash('Title is required!')
        else:
            current_post = Post(author_id=author_id, title=title, content=content)
            db.session.add(current_post)
            db.session.commit()
            return redirect(url_for('posts.index'))
        
    return render_template('posts/create.html')

@bp.route('/<int:id>/edit', methods=('GET', 'POST'))
@login_required
def edit(id):
    post = get_post(id)

    if post.author_id != current_user.id:
        flash('You are not the author of this post')
        return redirect(url_for('posts.index'))

    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']

        if not title:
            flash('Title is required')
        else:
            post.title = title
            post.content = content
            db.session.add(post)
            db.session.commit()
            flash('Sucessfully edited the post')
            return redirect(url_for('posts.index'))
    
    return render_template('posts/edit.html', post = post)

@bp.route('<int:id>/delete>', methods=('POST',))
def delete(id):
    post = get_post(id)

    if post.author_id != current_user.id:
        flash('You are not the author of this post')
        return redirect(url_for('posts.index'))
    
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('posts.index'))

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    <section class="hero is-primary is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                                <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                    Profile
                                </a>
                                <a href="{{ url_for('posts.index') }}" class="navbar-item">
                                    Posts
                                </a>
                                <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                    Logout
                                </a>
                            {% else %}
                                <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                    Login
                                </a>
                                <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                    Sign Up
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>

app/templates/baseAnonymous.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    <section class="hero is-primary is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
    Flask Login Example
</h1>
<h2 class="subtitle">
    Easy authentication and authorization in Flask.
</h2>
{% endblock %}

app/templates/posts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('posts.index') }}">FlaskBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.profile') }}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('posts.create')}}">New Post</a>
            </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/posts/categories.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Categories {% endblock %}</h1></span>
    <div class="content">
        <h2>This is the categories page within the posts blueprint</h2>
    </div>
{% endblock %}

app/templates/posts/create.html
{% extends 'posts/base.html' %}

{% block content %}
<h1>{% block title %} Create a New Post {% endblock %}</h1>

<form method="post">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" placeholder="Post title" class="form-control"
            value="{{ request.form['title'] }}"></input>
    </div>

    <div class="form-group">
        <label for="content">Content</label>
        <textarea name="content" placeholder="Post content"
            class="form-control">{{ request.form['content'] }}</textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock %}

app/templates/posts/edit.html
{% extends 'posts/base.html' %}

{% block content %}
<h1>{% block title %} Edit "{{ post['title'] }}" {% endblock %}</h1>

<form method="post">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" placeholder="Post title"
               class="form-control"
               value="{{ request.form['title'] or post['title'] }}">
        </input>
    </div>

    <div class="form-group">
        <label for="content">Content</label>
        <textarea name="content" placeholder="Post content"
                  class="form-control">{{ request.form['content'] or post['content'] }}</textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
<hr>
<form action="{{ url_for('posts.delete', id=post['id']) }}" method="POST">
    <input type="submit" value="Delete Post"
            class="btn btn-danger btn-sm"
            onclick="return confirm('Are you sure you want to delete this post?')">
</form>
{% endblock %}

app/templates/posts/index.html
{% extends 'posts/base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} The Posts Page {% endblock %}</h1></span>
    {% for post in posts %}
    <a href="{{ url_for('posts.post', post_id=post['id']) }}">
        <h2>{{ post['title'] }}</h2>
    </a>
    <span class="badge badge-primary">{{ post['published_at'] }}</span>
    {% if post['author_id'] == author_id %}
    <a href="{{ url_for('posts.edit', id=post['id']) }}">
        <span class="badge badge-warning">Edit</span>
    </a>
    {% endif %}
    <hr>
    {% endfor %}
{% endblock %}

app/templates/posts/post.html
{% extends 'posts/base.html' %}

{% block content %}
    <h2>{% block title %} {{ post['title'] }} {% endblock %}</h2>
    <span class="badge badge-primary">{{ post['published_at'] }}</span>
    <p>{{ post['content'] }}</p>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>
{% endblock %}